#
# This Makefile was generated by Code::Blocks IDE.
#

SRCS_f90d1 = \
ray.f90 \
vec3.f90 

SRCS_f90d2 = \
main.f90 

SRCS_modd3 = \
class_ray.mod \
class_vec3.mod \
utils.mod 

SRCS_od4 = \
ray.o \
vec3.o 

SRCS_od3 = \
main.o 

SRCS_dependd2 = \
raytracing-fortran.depend 

SRCS_layoutd2 = \
raytracing-fortran.layout 

OBJS_f90d1 = \
ray.o \
vec3.o 

OBJS_f90d2 = \
main.o 

OBJS_modd3 = \


OBJS_od4 = \


OBJS_od3 = \


OBJS_dependd2 = \


OBJS_layoutd2 = \


SRC_DIR_f90d1 = include/

SRC_DIR_f90d2 = 

SRC_DIR_modd3 = obj/Debug/

SRC_DIR_od4 = obj/Debug/include/

SRC_DIR_od3 = obj/Debug/

SRC_DIR_dependd2 = 

SRC_DIR_layoutd2 = 
OBJS_DIR = obj/Debug/include/
EXE_DIR = bin/Debug/

EXE = raytracing-fortran
FC = gfortran
LD = gfortran
IDIR = 
CFLAGS = -Wall -g -ffast-math -flto  -J$(OBJS_DIR) $(IDIR)
LFLAGS = 
LIBS = 

VPATH = $(SRC_DIR_f90d1):$(OBJS_DIR):$(SRC_DIR_f90d2):$(OBJS_DIR):$(SRC_DIR_modd3):$(OBJS_DIR):$(SRC_DIR_od4):$(OBJS_DIR):$(SRC_DIR_od3):$(OBJS_DIR):$(SRC_DIR_dependd2):$(OBJS_DIR):$(SRC_DIR_layoutd2):$(OBJS_DIR)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_f90d1) $(OBJS_f90d2) $(OBJS_modd3) $(OBJS_od4) $(OBJS_od3) $(OBJS_dependd2) $(OBJS_layoutd2))

all : $(EXE)

$(EXE) : $(OBJS_f90d1) $(OBJS_f90d2) $(OBJS_modd3) $(OBJS_od4) $(OBJS_od3) $(OBJS_dependd2) $(OBJS_layoutd2)
	@mkdir -p $(EXE_DIR)
	$(LD) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_f90d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d1)$(@:.o=.f90) -o $(OBJS_DIR)$@

$(OBJS_f90d2):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d2)$(@:.o=.f90) -o $(OBJS_DIR)$@

$(OBJS_modd3):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_modd3)$(@:.o=.mod) -o $(OBJS_DIR)$@

$(OBJS_od4):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_od4)$(@:.o=.o) -o $(OBJS_DIR)$@

$(OBJS_od3):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_od3)$(@:.o=.o) -o $(OBJS_DIR)$@

$(OBJS_dependd2):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_dependd2)$(@:.o=.depend) -o $(OBJS_DIR)$@

$(OBJS_layoutd2):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_layoutd2)$(@:.o=.layout) -o $(OBJS_DIR)$@

clean :
	rm -f $(OBJS_DIR)*.*
	rm -f $(EXE_DIR)$(EXE)

# File dependencies
ray.o: \
    ray.f90 \
    vec3.o
vec3.o: \
    vec3.f90
main.o: \
    main.f90 \
    ray.o \
    vec3.o

